/* ============================================================
   GeoQuest - Base de datos de países / Country database
   Banderas vía flagcdn.com (CDN gratuito, sin auth)
   Cada país: code (ISO2), name {en, es}, capital {en, es},
   continent, population, area (km2), latlng [lat, lng]
   ============================================================ */

const CONTINENTS = {
  AF: { en: "Africa", es: "África" },
  AN: { en: "Antarctica", es: "Antártida" },
  AS: { en: "Asia", es: "Asia" },
  EU: { en: "Europe", es: "Europa" },
  NA: { en: "North America", es: "América del Norte" },
  OC: { en: "Oceania", es: "Oceanía" },
  SA: { en: "South America", es: "América del Sur" }
};

const COUNTRIES = [
  { code: "af", name: { en: "Afghanistan", es: "Afganistán" }, capital: { en: "Kabul", es: "Kabul" }, continent: "AS", population: 38928000, area: 652230, latlng: [33, 65] },
  { code: "al", name: { en: "Albania", es: "Albania" }, capital: { en: "Tirana", es: "Tirana" }, continent: "EU", population: 2877000, area: 28748, latlng: [41, 20] },
  { code: "dz", name: { en: "Algeria", es: "Argelia" }, capital: { en: "Algiers", es: "Argel" }, continent: "AF", population: 43851000, area: 2381741, latlng: [28, 3] },
  { code: "ad", name: { en: "Andorra", es: "Andorra" }, capital: { en: "Andorra la Vella", es: "Andorra la Vieja" }, continent: "EU", population: 77265, area: 468, latlng: [42.5, 1.5] },
  { code: "ao", name: { en: "Angola", es: "Angola" }, capital: { en: "Luanda", es: "Luanda" }, continent: "AF", population: 32866000, area: 1246700, latlng: [-12.5, 18.5] },
  { code: "ag", name: { en: "Antigua and Barbuda", es: "Antigua y Barbuda" }, capital: { en: "Saint John's", es: "Saint John's" }, continent: "NA", population: 97929, area: 442, latlng: [17.05, -61.8] },
  { code: "ar", name: { en: "Argentina", es: "Argentina" }, capital: { en: "Buenos Aires", es: "Buenos Aires" }, continent: "SA", population: 45195000, area: 2780400, latlng: [-34, -64] },
  { code: "am", name: { en: "Armenia", es: "Armenia" }, capital: { en: "Yerevan", es: "Ereván" }, continent: "AS", population: 2963000, area: 29743, latlng: [40, 45] },
  { code: "au", name: { en: "Australia", es: "Australia" }, capital: { en: "Canberra", es: "Canberra" }, continent: "OC", population: 25499000, area: 7692024, latlng: [-27, 133] },
  { code: "at", name: { en: "Austria", es: "Austria" }, capital: { en: "Vienna", es: "Viena" }, continent: "EU", population: 9006000, area: 83871, latlng: [47.33, 13.33] },
  { code: "az", name: { en: "Azerbaijan", es: "Azerbaiyán" }, capital: { en: "Baku", es: "Bakú" }, continent: "AS", population: 10139000, area: 86600, latlng: [40.5, 47.5] },
  { code: "bs", name: { en: "Bahamas", es: "Bahamas" }, capital: { en: "Nassau", es: "Nasáu" }, continent: "NA", population: 393000, area: 13943, latlng: [24.25, -76] },
  { code: "bh", name: { en: "Bahrain", es: "Baréin" }, capital: { en: "Manama", es: "Manama" }, continent: "AS", population: 1701000, area: 765, latlng: [26, 50.55] },
  { code: "bd", name: { en: "Bangladesh", es: "Bangladés" }, capital: { en: "Dhaka", es: "Daca" }, continent: "AS", population: 164689000, area: 147570, latlng: [24, 90] },
  { code: "bb", name: { en: "Barbados", es: "Barbados" }, capital: { en: "Bridgetown", es: "Bridgetown" }, continent: "NA", population: 287000, area: 430, latlng: [13.17, -59.53] },
  { code: "by", name: { en: "Belarus", es: "Bielorrusia" }, capital: { en: "Minsk", es: "Minsk" }, continent: "EU", population: 9449000, area: 207600, latlng: [53, 28] },
  { code: "be", name: { en: "Belgium", es: "Bélgica" }, capital: { en: "Brussels", es: "Bruselas" }, continent: "EU", population: 11589000, area: 30528, latlng: [50.83, 4] },
  { code: "bz", name: { en: "Belize", es: "Belice" }, capital: { en: "Belmopan", es: "Belmopán" }, continent: "NA", population: 397000, area: 22966, latlng: [17.25, -88.75] },
  { code: "bj", name: { en: "Benin", es: "Benín" }, capital: { en: "Porto-Novo", es: "Porto Novo" }, continent: "AF", population: 12123000, area: 112622, latlng: [9.5, 2.25] },
  { code: "bt", name: { en: "Bhutan", es: "Bután" }, capital: { en: "Thimphu", es: "Timbu" }, continent: "AS", population: 771000, area: 38394, latlng: [27.5, 90.5] },
  { code: "bo", name: { en: "Bolivia", es: "Bolivia" }, capital: { en: "Sucre", es: "Sucre" }, continent: "SA", population: 11673000, area: 1098581, latlng: [-17, -65] },
  { code: "ba", name: { en: "Bosnia and Herzegovina", es: "Bosnia y Herzegovina" }, capital: { en: "Sarajevo", es: "Sarajevo" }, continent: "EU", population: 3281000, area: 51209, latlng: [44, 18] },
  { code: "bw", name: { en: "Botswana", es: "Botsuana" }, capital: { en: "Gaborone", es: "Gaborone" }, continent: "AF", population: 2351000, area: 582000, latlng: [-22, 24] },
  { code: "br", name: { en: "Brazil", es: "Brasil" }, capital: { en: "Brasília", es: "Brasilia" }, continent: "SA", population: 212559000, area: 8515767, latlng: [-10, -55] },
  { code: "bn", name: { en: "Brunei", es: "Brunéi" }, capital: { en: "Bandar Seri Begawan", es: "Bandar Seri Begawan" }, continent: "AS", population: 437000, area: 5765, latlng: [4.5, 114.67] },
  { code: "bg", name: { en: "Bulgaria", es: "Bulgaria" }, capital: { en: "Sofia", es: "Sofía" }, continent: "EU", population: 6948000, area: 110879, latlng: [43, 25] },
  { code: "bf", name: { en: "Burkina Faso", es: "Burkina Faso" }, capital: { en: "Ouagadougou", es: "Uagadugú" }, continent: "AF", population: 20903000, area: 272967, latlng: [13, -2] },
  { code: "bi", name: { en: "Burundi", es: "Burundi" }, capital: { en: "Gitega", es: "Gitega" }, continent: "AF", population: 11891000, area: 27834, latlng: [-3.5, 30] },
  { code: "kh", name: { en: "Cambodia", es: "Camboya" }, capital: { en: "Phnom Penh", es: "Nom Pen" }, continent: "AS", population: 16719000, area: 181035, latlng: [13, 105] },
  { code: "cm", name: { en: "Cameroon", es: "Camerún" }, capital: { en: "Yaoundé", es: "Yaundé" }, continent: "AF", population: 26546000, area: 475442, latlng: [6, 12] },
  { code: "ca", name: { en: "Canada", es: "Canadá" }, capital: { en: "Ottawa", es: "Ottawa" }, continent: "NA", population: 37742000, area: 9984670, latlng: [60, -95] },
  { code: "cv", name: { en: "Cape Verde", es: "Cabo Verde" }, capital: { en: "Praia", es: "Praia" }, continent: "AF", population: 555987, area: 4033, latlng: [16, -24] },
  { code: "cf", name: { en: "Central African Republic", es: "República Centroafricana" }, capital: { en: "Bangui", es: "Bangui" }, continent: "AF", population: 4830000, area: 622984, latlng: [7, 21] },
  { code: "td", name: { en: "Chad", es: "Chad" }, capital: { en: "N'Djamena", es: "Yamena" }, continent: "AF", population: 16426000, area: 1284000, latlng: [15, 19] },
  { code: "cl", name: { en: "Chile", es: "Chile" }, capital: { en: "Santiago", es: "Santiago" }, continent: "SA", population: 19116000, area: 756102, latlng: [-30, -71] },
  { code: "cn", name: { en: "China", es: "China" }, capital: { en: "Beijing", es: "Pekín" }, continent: "AS", population: 1439324000, area: 9596961, latlng: [35, 105] },
  { code: "co", name: { en: "Colombia", es: "Colombia" }, capital: { en: "Bogotá", es: "Bogotá" }, continent: "SA", population: 50883000, area: 1141748, latlng: [4, -72] },
  { code: "km", name: { en: "Comoros", es: "Comoras" }, capital: { en: "Moroni", es: "Moroni" }, continent: "AF", population: 869601, area: 1862, latlng: [-12.17, 44.25] },
  { code: "cg", name: { en: "Republic of the Congo", es: "República del Congo" }, capital: { en: "Brazzaville", es: "Brazzaville" }, continent: "AF", population: 5518000, area: 342000, latlng: [-1, 15] },
  { code: "cd", name: { en: "DR Congo", es: "RD del Congo" }, capital: { en: "Kinshasa", es: "Kinsasa" }, continent: "AF", population: 89561000, area: 2344858, latlng: [0, 25] },
  { code: "cr", name: { en: "Costa Rica", es: "Costa Rica" }, capital: { en: "San José", es: "San José" }, continent: "NA", population: 5094000, area: 51100, latlng: [10, -84] },
  { code: "ci", name: { en: "Ivory Coast", es: "Costa de Marfil" }, capital: { en: "Yamoussoukro", es: "Yamusukro" }, continent: "AF", population: 26378000, area: 322463, latlng: [8, -5] },
  { code: "hr", name: { en: "Croatia", es: "Croacia" }, capital: { en: "Zagreb", es: "Zagreb" }, continent: "EU", population: 4105000, area: 56594, latlng: [45.17, 15.5] },
  { code: "cu", name: { en: "Cuba", es: "Cuba" }, capital: { en: "Havana", es: "La Habana" }, continent: "NA", population: 11327000, area: 109884, latlng: [21.5, -80] },
  { code: "cy", name: { en: "Cyprus", es: "Chipre" }, capital: { en: "Nicosia", es: "Nicosia" }, continent: "EU", population: 1207000, area: 9251, latlng: [35, 33] },
  { code: "cz", name: { en: "Czechia", es: "República Checa" }, capital: { en: "Prague", es: "Praga" }, continent: "EU", population: 10709000, area: 78865, latlng: [49.75, 15.5] },
  { code: "dk", name: { en: "Denmark", es: "Dinamarca" }, capital: { en: "Copenhagen", es: "Copenhague" }, continent: "EU", population: 5792000, area: 43094, latlng: [56, 10] },
  { code: "dj", name: { en: "Djibouti", es: "Yibuti" }, capital: { en: "Djibouti", es: "Yibuti" }, continent: "AF", population: 988000, area: 23200, latlng: [11.5, 43] },
  { code: "dm", name: { en: "Dominica", es: "Dominica" }, capital: { en: "Roseau", es: "Roseau" }, continent: "NA", population: 71986, area: 751, latlng: [15.42, -61.33] },
  { code: "do", name: { en: "Dominican Republic", es: "República Dominicana" }, capital: { en: "Santo Domingo", es: "Santo Domingo" }, continent: "NA", population: 10848000, area: 48671, latlng: [19, -70.67] },
  { code: "ec", name: { en: "Ecuador", es: "Ecuador" }, capital: { en: "Quito", es: "Quito" }, continent: "SA", population: 17643000, area: 283561, latlng: [-2, -77.5] },
  { code: "eg", name: { en: "Egypt", es: "Egipto" }, capital: { en: "Cairo", es: "El Cairo" }, continent: "AF", population: 102334000, area: 1002450, latlng: [27, 30] },
  { code: "sv", name: { en: "El Salvador", es: "El Salvador" }, capital: { en: "San Salvador", es: "San Salvador" }, continent: "NA", population: 6486000, area: 21041, latlng: [13.83, -88.92] },
  { code: "gq", name: { en: "Equatorial Guinea", es: "Guinea Ecuatorial" }, capital: { en: "Malabo", es: "Malabo" }, continent: "AF", population: 1403000, area: 28051, latlng: [2, 10] },
  { code: "er", name: { en: "Eritrea", es: "Eritrea" }, capital: { en: "Asmara", es: "Asmara" }, continent: "AF", population: 3546000, area: 117600, latlng: [15, 39] },
  { code: "ee", name: { en: "Estonia", es: "Estonia" }, capital: { en: "Tallinn", es: "Tallin" }, continent: "EU", population: 1326000, area: 45227, latlng: [59, 26] },
  { code: "sz", name: { en: "Eswatini", es: "Esuatini" }, capital: { en: "Mbabane", es: "Mbabane" }, continent: "AF", population: 1160000, area: 17364, latlng: [-26.5, 31.5] },
  { code: "et", name: { en: "Ethiopia", es: "Etiopía" }, capital: { en: "Addis Ababa", es: "Adís Abeba" }, continent: "AF", population: 114964000, area: 1104300, latlng: [8, 38] },
  { code: "fj", name: { en: "Fiji", es: "Fiyi" }, capital: { en: "Suva", es: "Suva" }, continent: "OC", population: 896000, area: 18272, latlng: [-18, 175] },
  { code: "fi", name: { en: "Finland", es: "Finlandia" }, capital: { en: "Helsinki", es: "Helsinki" }, continent: "EU", population: 5540000, area: 338424, latlng: [64, 26] },
  { code: "fr", name: { en: "France", es: "Francia" }, capital: { en: "Paris", es: "París" }, continent: "EU", population: 65274000, area: 551695, latlng: [46, 2] },
  { code: "ga", name: { en: "Gabon", es: "Gabón" }, capital: { en: "Libreville", es: "Libreville" }, continent: "AF", population: 2225000, area: 267668, latlng: [-1, 11.75] },
  { code: "gm", name: { en: "Gambia", es: "Gambia" }, capital: { en: "Banjul", es: "Banjul" }, continent: "AF", population: 2417000, area: 11295, latlng: [13.47, -16.57] },
  { code: "ge", name: { en: "Georgia", es: "Georgia" }, capital: { en: "Tbilisi", es: "Tiflis" }, continent: "AS", population: 3989000, area: 69700, latlng: [42, 43.5] },
  { code: "de", name: { en: "Germany", es: "Alemania" }, capital: { en: "Berlin", es: "Berlín" }, continent: "EU", population: 83784000, area: 357114, latlng: [51, 9] },
  { code: "gh", name: { en: "Ghana", es: "Ghana" }, capital: { en: "Accra", es: "Acra" }, continent: "AF", population: 31073000, area: 238533, latlng: [8, -2] },
  { code: "gr", name: { en: "Greece", es: "Grecia" }, capital: { en: "Athens", es: "Atenas" }, continent: "EU", population: 10423000, area: 131990, latlng: [39, 22] },
  { code: "gd", name: { en: "Grenada", es: "Granada" }, capital: { en: "Saint George's", es: "Saint George's" }, continent: "NA", population: 112523, area: 344, latlng: [12.12, -61.67] },
  { code: "gt", name: { en: "Guatemala", es: "Guatemala" }, capital: { en: "Guatemala City", es: "Ciudad de Guatemala" }, continent: "NA", population: 17916000, area: 108889, latlng: [15.5, -90.25] },
  { code: "gn", name: { en: "Guinea", es: "Guinea" }, capital: { en: "Conakry", es: "Conakri" }, continent: "AF", population: 13133000, area: 245857, latlng: [11, -10] },
  { code: "gw", name: { en: "Guinea-Bissau", es: "Guinea-Bisáu" }, capital: { en: "Bissau", es: "Bisáu" }, continent: "AF", population: 1968000, area: 36125, latlng: [12, -15] },
  { code: "gy", name: { en: "Guyana", es: "Guyana" }, capital: { en: "Georgetown", es: "Georgetown" }, continent: "SA", population: 786000, area: 214969, latlng: [5, -59] },
  { code: "ht", name: { en: "Haiti", es: "Haití" }, capital: { en: "Port-au-Prince", es: "Puerto Príncipe" }, continent: "NA", population: 11403000, area: 27750, latlng: [19, -72.42] },
  { code: "hn", name: { en: "Honduras", es: "Honduras" }, capital: { en: "Tegucigalpa", es: "Tegucigalpa" }, continent: "NA", population: 9905000, area: 112492, latlng: [15, -86.5] },
  { code: "hu", name: { en: "Hungary", es: "Hungría" }, capital: { en: "Budapest", es: "Budapest" }, continent: "EU", population: 9660000, area: 93028, latlng: [47, 20] },
  { code: "is", name: { en: "Iceland", es: "Islandia" }, capital: { en: "Reykjavík", es: "Reikiavik" }, continent: "EU", population: 341000, area: 103000, latlng: [65, -18] },
  { code: "in", name: { en: "India", es: "India" }, capital: { en: "New Delhi", es: "Nueva Delhi" }, continent: "AS", population: 1380004000, area: 3287590, latlng: [20, 77] },
  { code: "id", name: { en: "Indonesia", es: "Indonesia" }, capital: { en: "Jakarta", es: "Yakarta" }, continent: "AS", population: 273524000, area: 1904569, latlng: [-5, 120] },
  { code: "ir", name: { en: "Iran", es: "Irán" }, capital: { en: "Tehran", es: "Teherán" }, continent: "AS", population: 83993000, area: 1648195, latlng: [32, 53] },
  { code: "iq", name: { en: "Iraq", es: "Irak" }, capital: { en: "Baghdad", es: "Bagdad" }, continent: "AS", population: 40223000, area: 438317, latlng: [33, 44] },
  { code: "ie", name: { en: "Ireland", es: "Irlanda" }, capital: { en: "Dublin", es: "Dublín" }, continent: "EU", population: 4938000, area: 70273, latlng: [53, -8] },
  { code: "il", name: { en: "Israel", es: "Israel" }, capital: { en: "Jerusalem", es: "Jerusalén" }, continent: "AS", population: 8656000, area: 20770, latlng: [31.5, 34.75] },
  { code: "it", name: { en: "Italy", es: "Italia" }, capital: { en: "Rome", es: "Roma" }, continent: "EU", population: 60461000, area: 301336, latlng: [42.83, 12.83] },
  { code: "jm", name: { en: "Jamaica", es: "Jamaica" }, capital: { en: "Kingston", es: "Kingston" }, continent: "NA", population: 2961000, area: 10991, latlng: [18.25, -77.5] },
  { code: "jp", name: { en: "Japan", es: "Japón" }, capital: { en: "Tokyo", es: "Tokio" }, continent: "AS", population: 126476000, area: 377930, latlng: [36, 138] },
  { code: "jo", name: { en: "Jordan", es: "Jordania" }, capital: { en: "Amman", es: "Amán" }, continent: "AS", population: 10203000, area: 89342, latlng: [31, 36] },
  { code: "kz", name: { en: "Kazakhstan", es: "Kazajistán" }, capital: { en: "Astana", es: "Astaná" }, continent: "AS", population: 18777000, area: 2724900, latlng: [48, 68] },
  { code: "ke", name: { en: "Kenya", es: "Kenia" }, capital: { en: "Nairobi", es: "Nairobi" }, continent: "AF", population: 53771000, area: 580367, latlng: [1, 38] },
  { code: "ki", name: { en: "Kiribati", es: "Kiribati" }, capital: { en: "Tarawa", es: "Tarawa" }, continent: "OC", population: 119449, area: 811, latlng: [1.42, 173] },
  { code: "kw", name: { en: "Kuwait", es: "Kuwait" }, capital: { en: "Kuwait City", es: "Ciudad de Kuwait" }, continent: "AS", population: 4271000, area: 17818, latlng: [29.5, 47.75] },
  { code: "kg", name: { en: "Kyrgyzstan", es: "Kirguistán" }, capital: { en: "Bishkek", es: "Biskek" }, continent: "AS", population: 6524000, area: 199951, latlng: [41, 75] },
  { code: "la", name: { en: "Laos", es: "Laos" }, capital: { en: "Vientiane", es: "Vientián" }, continent: "AS", population: 7276000, area: 236800, latlng: [18, 105] },
  { code: "lv", name: { en: "Latvia", es: "Letonia" }, capital: { en: "Riga", es: "Riga" }, continent: "EU", population: 1886000, area: 64589, latlng: [57, 25] },
  { code: "lb", name: { en: "Lebanon", es: "Líbano" }, capital: { en: "Beirut", es: "Beirut" }, continent: "AS", population: 6825000, area: 10452, latlng: [33.83, 35.83] },
  { code: "ls", name: { en: "Lesotho", es: "Lesoto" }, capital: { en: "Maseru", es: "Maseru" }, continent: "AF", population: 2142000, area: 30355, latlng: [-29.5, 28.5] },
  { code: "lr", name: { en: "Liberia", es: "Liberia" }, capital: { en: "Monrovia", es: "Monrovia" }, continent: "AF", population: 5058000, area: 111369, latlng: [6.5, -9.5] },
  { code: "ly", name: { en: "Libya", es: "Libia" }, capital: { en: "Tripoli", es: "Trípoli" }, continent: "AF", population: 6871000, area: 1759540, latlng: [25, 17] },
  { code: "li", name: { en: "Liechtenstein", es: "Liechtenstein" }, capital: { en: "Vaduz", es: "Vaduz" }, continent: "EU", population: 38128, area: 160, latlng: [47.17, 9.53] },
  { code: "lt", name: { en: "Lithuania", es: "Lituania" }, capital: { en: "Vilnius", es: "Vilna" }, continent: "EU", population: 2722000, area: 65300, latlng: [56, 24] },
  { code: "lu", name: { en: "Luxembourg", es: "Luxemburgo" }, capital: { en: "Luxembourg", es: "Luxemburgo" }, continent: "EU", population: 625978, area: 2586, latlng: [49.75, 6.17] },
  { code: "mg", name: { en: "Madagascar", es: "Madagascar" }, capital: { en: "Antananarivo", es: "Antananarivo" }, continent: "AF", population: 27691000, area: 587041, latlng: [-20, 47] },
  { code: "mw", name: { en: "Malawi", es: "Malaui" }, capital: { en: "Lilongwe", es: "Lilongüe" }, continent: "AF", population: 19130000, area: 118484, latlng: [-13.5, 34] },
  { code: "my", name: { en: "Malaysia", es: "Malasia" }, capital: { en: "Kuala Lumpur", es: "Kuala Lumpur" }, continent: "AS", population: 32366000, area: 330803, latlng: [2.5, 112.5] },
  { code: "mv", name: { en: "Maldives", es: "Maldivas" }, capital: { en: "Malé", es: "Malé" }, continent: "AS", population: 540544, area: 300, latlng: [3.25, 73] },
  { code: "ml", name: { en: "Mali", es: "Malí" }, capital: { en: "Bamako", es: "Bamako" }, continent: "AF", population: 20251000, area: 1240192, latlng: [17, -4] },
  { code: "mt", name: { en: "Malta", es: "Malta" }, capital: { en: "Valletta", es: "La Valeta" }, continent: "EU", population: 441543, area: 316, latlng: [35.83, 14.58] },
  { code: "mh", name: { en: "Marshall Islands", es: "Islas Marshall" }, capital: { en: "Majuro", es: "Majuro" }, continent: "OC", population: 59190, area: 181, latlng: [9, 168] },
  { code: "mr", name: { en: "Mauritania", es: "Mauritania" }, capital: { en: "Nouakchott", es: "Nuakchot" }, continent: "AF", population: 4650000, area: 1030700, latlng: [20, -12] },
  { code: "mu", name: { en: "Mauritius", es: "Mauricio" }, capital: { en: "Port Louis", es: "Port Louis" }, continent: "AF", population: 1272000, area: 2040, latlng: [-20.28, 57.55] },
  { code: "mx", name: { en: "Mexico", es: "México" }, capital: { en: "Mexico City", es: "Ciudad de México" }, continent: "NA", population: 128933000, area: 1964375, latlng: [23, -102] },
  { code: "fm", name: { en: "Micronesia", es: "Micronesia" }, capital: { en: "Palikir", es: "Palikir" }, continent: "OC", population: 115023, area: 702, latlng: [6.92, 158.25] },
  { code: "md", name: { en: "Moldova", es: "Moldavia" }, capital: { en: "Chișinău", es: "Chisináu" }, continent: "EU", population: 4034000, area: 33846, latlng: [47, 29] },
  { code: "mc", name: { en: "Monaco", es: "Mónaco" }, capital: { en: "Monaco", es: "Mónaco" }, continent: "EU", population: 39242, area: 2, latlng: [43.73, 7.4] },
  { code: "mn", name: { en: "Mongolia", es: "Mongolia" }, capital: { en: "Ulaanbaatar", es: "Ulán Bator" }, continent: "AS", population: 3278000, area: 1564110, latlng: [46, 105] },
  { code: "me", name: { en: "Montenegro", es: "Montenegro" }, capital: { en: "Podgorica", es: "Podgorica" }, continent: "EU", population: 628066, area: 13812, latlng: [42.5, 19.3] },
  { code: "ma", name: { en: "Morocco", es: "Marruecos" }, capital: { en: "Rabat", es: "Rabat" }, continent: "AF", population: 36911000, area: 446550, latlng: [32, -5] },
  { code: "mz", name: { en: "Mozambique", es: "Mozambique" }, capital: { en: "Maputo", es: "Maputo" }, continent: "AF", population: 31255000, area: 801590, latlng: [-18.25, 35] },
  { code: "mm", name: { en: "Myanmar", es: "Birmania" }, capital: { en: "Naypyidaw", es: "Naipyidó" }, continent: "AS", population: 54410000, area: 676578, latlng: [22, 98] },
  { code: "na", name: { en: "Namibia", es: "Namibia" }, capital: { en: "Windhoek", es: "Windhoek" }, continent: "AF", population: 2541000, area: 825615, latlng: [-22, 17] },
  { code: "nr", name: { en: "Nauru", es: "Nauru" }, capital: { en: "Yaren", es: "Yaren" }, continent: "OC", population: 10824, area: 21, latlng: [-0.53, 166.92] },
  { code: "np", name: { en: "Nepal", es: "Nepal" }, capital: { en: "Kathmandu", es: "Katmandú" }, continent: "AS", population: 29137000, area: 147181, latlng: [28, 84] },
  { code: "nl", name: { en: "Netherlands", es: "Países Bajos" }, capital: { en: "Amsterdam", es: "Ámsterdam" }, continent: "EU", population: 17135000, area: 41850, latlng: [52.5, 5.75] },
  { code: "nz", name: { en: "New Zealand", es: "Nueva Zelanda" }, capital: { en: "Wellington", es: "Wellington" }, continent: "OC", population: 4822000, area: 270467, latlng: [-41, 174] },
  { code: "ni", name: { en: "Nicaragua", es: "Nicaragua" }, capital: { en: "Managua", es: "Managua" }, continent: "NA", population: 6624000, area: 130373, latlng: [13, -85] },
  { code: "ne", name: { en: "Niger", es: "Níger" }, capital: { en: "Niamey", es: "Niamey" }, continent: "AF", population: 24207000, area: 1267000, latlng: [16, 8] },
  { code: "ng", name: { en: "Nigeria", es: "Nigeria" }, capital: { en: "Abuja", es: "Abuya" }, continent: "AF", population: 206139000, area: 923768, latlng: [10, 8] },
  { code: "kp", name: { en: "North Korea", es: "Corea del Norte" }, capital: { en: "Pyongyang", es: "Pionyang" }, continent: "AS", population: 25778000, area: 120538, latlng: [40, 127] },
  { code: "mk", name: { en: "North Macedonia", es: "Macedonia del Norte" }, capital: { en: "Skopje", es: "Skopie" }, continent: "EU", population: 2083000, area: 25713, latlng: [41.83, 22] },
  { code: "no", name: { en: "Norway", es: "Noruega" }, capital: { en: "Oslo", es: "Oslo" }, continent: "EU", population: 5421000, area: 323802, latlng: [62, 10] },
  { code: "om", name: { en: "Oman", es: "Omán" }, capital: { en: "Muscat", es: "Mascate" }, continent: "AS", population: 5107000, area: 309500, latlng: [21, 57] },
  { code: "pk", name: { en: "Pakistan", es: "Pakistán" }, capital: { en: "Islamabad", es: "Islamabad" }, continent: "AS", population: 220892000, area: 881912, latlng: [30, 70] },
  { code: "pw", name: { en: "Palau", es: "Palaos" }, capital: { en: "Ngerulmud", es: "Ngerulmud" }, continent: "OC", population: 18094, area: 459, latlng: [7.5, 134.5] },
  { code: "pa", name: { en: "Panama", es: "Panamá" }, capital: { en: "Panama City", es: "Ciudad de Panamá" }, continent: "NA", population: 4314000, area: 75417, latlng: [9, -80] },
  { code: "pg", name: { en: "Papua New Guinea", es: "Papúa Nueva Guinea" }, capital: { en: "Port Moresby", es: "Port Moresby" }, continent: "OC", population: 8947000, area: 462840, latlng: [-6, 147] },
  { code: "py", name: { en: "Paraguay", es: "Paraguay" }, capital: { en: "Asunción", es: "Asunción" }, continent: "SA", population: 7133000, area: 406752, latlng: [-23, -58] },
  { code: "pe", name: { en: "Peru", es: "Perú" }, capital: { en: "Lima", es: "Lima" }, continent: "SA", population: 32972000, area: 1285216, latlng: [-10, -76] },
  { code: "ph", name: { en: "Philippines", es: "Filipinas" }, capital: { en: "Manila", es: "Manila" }, continent: "AS", population: 109581000, area: 342353, latlng: [13, 122] },
  { code: "pl", name: { en: "Poland", es: "Polonia" }, capital: { en: "Warsaw", es: "Varsovia" }, continent: "EU", population: 37846000, area: 312696, latlng: [52, 20] },
  { code: "pt", name: { en: "Portugal", es: "Portugal" }, capital: { en: "Lisbon", es: "Lisboa" }, continent: "EU", population: 10196000, area: 92090, latlng: [39.5, -8] },
  { code: "qa", name: { en: "Qatar", es: "Catar" }, capital: { en: "Doha", es: "Doha" }, continent: "AS", population: 2881000, area: 11586, latlng: [25.5, 51.25] },
  { code: "ro", name: { en: "Romania", es: "Rumanía" }, capital: { en: "Bucharest", es: "Bucarest" }, continent: "EU", population: 19237000, area: 238391, latlng: [46, 25] },
  { code: "ru", name: { en: "Russia", es: "Rusia" }, capital: { en: "Moscow", es: "Moscú" }, continent: "EU", population: 145934000, area: 17098242, latlng: [60, 100] },
  { code: "rw", name: { en: "Rwanda", es: "Ruanda" }, capital: { en: "Kigali", es: "Kigali" }, continent: "AF", population: 12952000, area: 26338, latlng: [-2, 30] },
  { code: "kn", name: { en: "Saint Kitts and Nevis", es: "San Cristóbal y Nieves" }, capital: { en: "Basseterre", es: "Basseterre" }, continent: "NA", population: 53199, area: 261, latlng: [17.33, -62.75] },
  { code: "lc", name: { en: "Saint Lucia", es: "Santa Lucía" }, capital: { en: "Castries", es: "Castries" }, continent: "NA", population: 183627, area: 616, latlng: [13.88, -60.97] },
  { code: "vc", name: { en: "Saint Vincent and the Grenadines", es: "San Vicente y las Granadinas" }, capital: { en: "Kingstown", es: "Kingstown" }, continent: "NA", population: 110940, area: 389, latlng: [13.25, -61.2] },
  { code: "ws", name: { en: "Samoa", es: "Samoa" }, capital: { en: "Apia", es: "Apia" }, continent: "OC", population: 198414, area: 2842, latlng: [-13.58, -172.33] },
  { code: "sm", name: { en: "San Marino", es: "San Marino" }, capital: { en: "San Marino", es: "San Marino" }, continent: "EU", population: 33931, area: 61, latlng: [43.93, 12.42] },
  { code: "st", name: { en: "São Tomé and Príncipe", es: "Santo Tomé y Príncipe" }, capital: { en: "São Tomé", es: "Santo Tomé" }, continent: "AF", population: 219159, area: 964, latlng: [1, 7] },
  { code: "sa", name: { en: "Saudi Arabia", es: "Arabia Saudita" }, capital: { en: "Riyadh", es: "Riad" }, continent: "AS", population: 34814000, area: 2149690, latlng: [25, 45] },
  { code: "sn", name: { en: "Senegal", es: "Senegal" }, capital: { en: "Dakar", es: "Dakar" }, continent: "AF", population: 16744000, area: 196722, latlng: [14, -14] },
  { code: "rs", name: { en: "Serbia", es: "Serbia" }, capital: { en: "Belgrade", es: "Belgrado" }, continent: "EU", population: 8737000, area: 88361, latlng: [44, 21] },
  { code: "sc", name: { en: "Seychelles", es: "Seychelles" }, capital: { en: "Victoria", es: "Victoria" }, continent: "AF", population: 98347, area: 452, latlng: [-4.58, 55.67] },
  { code: "sl", name: { en: "Sierra Leone", es: "Sierra Leona" }, capital: { en: "Freetown", es: "Freetown" }, continent: "AF", population: 7976000, area: 71740, latlng: [8.5, -11.5] },
  { code: "sg", name: { en: "Singapore", es: "Singapur" }, capital: { en: "Singapore", es: "Singapur" }, continent: "AS", population: 5850000, area: 710, latlng: [1.37, 103.8] },
  { code: "sk", name: { en: "Slovakia", es: "Eslovaquia" }, capital: { en: "Bratislava", es: "Bratislava" }, continent: "EU", population: 5459000, area: 49037, latlng: [48.67, 19.5] },
  { code: "si", name: { en: "Slovenia", es: "Eslovenia" }, capital: { en: "Ljubljana", es: "Liubliana" }, continent: "EU", population: 2078000, area: 20273, latlng: [46, 15] },
  { code: "sb", name: { en: "Solomon Islands", es: "Islas Salomón" }, capital: { en: "Honiara", es: "Honiara" }, continent: "OC", population: 686884, area: 28896, latlng: [-8, 159] },
  { code: "so", name: { en: "Somalia", es: "Somalia" }, capital: { en: "Mogadishu", es: "Mogadiscio" }, continent: "AF", population: 15893000, area: 637657, latlng: [10, 49] },
  { code: "za", name: { en: "South Africa", es: "Sudáfrica" }, capital: { en: "Pretoria", es: "Pretoria" }, continent: "AF", population: 59309000, area: 1221037, latlng: [-29, 24] },
  { code: "kr", name: { en: "South Korea", es: "Corea del Sur" }, capital: { en: "Seoul", es: "Seúl" }, continent: "AS", population: 51269000, area: 100210, latlng: [37, 127.5] },
  { code: "ss", name: { en: "South Sudan", es: "Sudán del Sur" }, capital: { en: "Juba", es: "Yuba" }, continent: "AF", population: 11194000, area: 619745, latlng: [7, 30] },
  { code: "es", name: { en: "Spain", es: "España" }, capital: { en: "Madrid", es: "Madrid" }, continent: "EU", population: 46755000, area: 505992, latlng: [40, -4] },
  { code: "lk", name: { en: "Sri Lanka", es: "Sri Lanka" }, capital: { en: "Sri Jayawardenepura Kotte", es: "Sri Jayawardenepura Kotte" }, continent: "AS", population: 21413000, area: 65610, latlng: [7, 81] },
  { code: "sd", name: { en: "Sudan", es: "Sudán" }, capital: { en: "Khartoum", es: "Jartum" }, continent: "AF", population: 43849000, area: 1886068, latlng: [15, 30] },
  { code: "sr", name: { en: "Suriname", es: "Surinam" }, capital: { en: "Paramaribo", es: "Paramaribo" }, continent: "SA", population: 586632, area: 163820, latlng: [4, -56] },
  { code: "se", name: { en: "Sweden", es: "Suecia" }, capital: { en: "Stockholm", es: "Estocolmo" }, continent: "EU", population: 10099000, area: 450295, latlng: [62, 15] },
  { code: "ch", name: { en: "Switzerland", es: "Suiza" }, capital: { en: "Bern", es: "Berna" }, continent: "EU", population: 8655000, area: 41284, latlng: [47, 8] },
  { code: "sy", name: { en: "Syria", es: "Siria" }, capital: { en: "Damascus", es: "Damasco" }, continent: "AS", population: 17501000, area: 185180, latlng: [35, 38] },
  { code: "tw", name: { en: "Taiwan", es: "Taiwán" }, capital: { en: "Taipei", es: "Taipéi" }, continent: "AS", population: 23817000, area: 36193, latlng: [23.5, 121] },
  { code: "tj", name: { en: "Tajikistan", es: "Tayikistán" }, capital: { en: "Dushanbe", es: "Dusambé" }, continent: "AS", population: 9538000, area: 143100, latlng: [39, 71] },
  { code: "tz", name: { en: "Tanzania", es: "Tanzania" }, capital: { en: "Dodoma", es: "Dodoma" }, continent: "AF", population: 59734000, area: 945087, latlng: [-6, 35] },
  { code: "th", name: { en: "Thailand", es: "Tailandia" }, capital: { en: "Bangkok", es: "Bangkok" }, continent: "AS", population: 69799000, area: 513120, latlng: [15, 100] },
  { code: "tl", name: { en: "Timor-Leste", es: "Timor Oriental" }, capital: { en: "Dili", es: "Dili" }, continent: "AS", population: 1318000, area: 14874, latlng: [-8.83, 125.92] },
  { code: "tg", name: { en: "Togo", es: "Togo" }, capital: { en: "Lomé", es: "Lomé" }, continent: "AF", population: 8279000, area: 56785, latlng: [8, 1.17] },
  { code: "to", name: { en: "Tonga", es: "Tonga" }, capital: { en: "Nuku'alofa", es: "Nukualofa" }, continent: "OC", population: 105695, area: 747, latlng: [-20, -175] },
  { code: "tt", name: { en: "Trinidad and Tobago", es: "Trinidad y Tobago" }, capital: { en: "Port of Spain", es: "Puerto España" }, continent: "NA", population: 1399000, area: 5130, latlng: [11, -61] },
  { code: "tn", name: { en: "Tunisia", es: "Túnez" }, capital: { en: "Tunis", es: "Túnez" }, continent: "AF", population: 11819000, area: 163610, latlng: [34, 9] },
  { code: "tr", name: { en: "Turkey", es: "Turquía" }, capital: { en: "Ankara", es: "Ankara" }, continent: "AS", population: 84339000, area: 783562, latlng: [39, 35] },
  { code: "tm", name: { en: "Turkmenistan", es: "Turkmenistán" }, capital: { en: "Ashgabat", es: "Asjabad" }, continent: "AS", population: 6031000, area: 488100, latlng: [40, 60] },
  { code: "tv", name: { en: "Tuvalu", es: "Tuvalu" }, capital: { en: "Funafuti", es: "Funafuti" }, continent: "OC", population: 11792, area: 26, latlng: [-8, 178] },
  { code: "ug", name: { en: "Uganda", es: "Uganda" }, capital: { en: "Kampala", es: "Kampala" }, continent: "AF", population: 45741000, area: 241550, latlng: [1, 32] },
  { code: "ua", name: { en: "Ukraine", es: "Ucrania" }, capital: { en: "Kyiv", es: "Kiev" }, continent: "EU", population: 43734000, area: 603500, latlng: [49, 32] },
  { code: "ae", name: { en: "United Arab Emirates", es: "Emiratos Árabes Unidos" }, capital: { en: "Abu Dhabi", es: "Abu Dabi" }, continent: "AS", population: 9890000, area: 83600, latlng: [24, 54] },
  { code: "gb", name: { en: "United Kingdom", es: "Reino Unido" }, capital: { en: "London", es: "Londres" }, continent: "EU", population: 67886000, area: 242900, latlng: [54, -2] },
  { code: "us", name: { en: "United States", es: "Estados Unidos" }, capital: { en: "Washington, D.C.", es: "Washington D. C." }, continent: "NA", population: 331003000, area: 9833517, latlng: [38, -97] },
  { code: "uy", name: { en: "Uruguay", es: "Uruguay" }, capital: { en: "Montevideo", es: "Montevideo" }, continent: "SA", population: 3474000, area: 181034, latlng: [-33, -56] },
  { code: "uz", name: { en: "Uzbekistan", es: "Uzbekistán" }, capital: { en: "Tashkent", es: "Taskent" }, continent: "AS", population: 33469000, area: 447400, latlng: [41, 64] },
  { code: "vu", name: { en: "Vanuatu", es: "Vanuatu" }, capital: { en: "Port Vila", es: "Port Vila" }, continent: "OC", population: 307145, area: 12189, latlng: [-16, 167] },
  { code: "va", name: { en: "Vatican City", es: "Ciudad del Vaticano" }, capital: { en: "Vatican City", es: "Ciudad del Vaticano" }, continent: "EU", population: 825, area: 0.49, latlng: [41.9, 12.45] },
  { code: "ve", name: { en: "Venezuela", es: "Venezuela" }, capital: { en: "Caracas", es: "Caracas" }, continent: "SA", population: 28436000, area: 916445, latlng: [8, -66] },
  { code: "vn", name: { en: "Vietnam", es: "Vietnam" }, capital: { en: "Hanoi", es: "Hanói" }, continent: "AS", population: 97339000, area: 331212, latlng: [16, 106] },
  { code: "ye", name: { en: "Yemen", es: "Yemen" }, capital: { en: "Sana'a", es: "Saná" }, continent: "AS", population: 29826000, area: 527968, latlng: [15, 48] },
  { code: "zm", name: { en: "Zambia", es: "Zambia" }, capital: { en: "Lusaka", es: "Lusaka" }, continent: "AF", population: 18384000, area: 752612, latlng: [-15, 30] },
  { code: "zw", name: { en: "Zimbabwe", es: "Zimbabue" }, capital: { en: "Harare", es: "Harare" }, continent: "AF", population: 14863000, area: 390757, latlng: [-20, 30] }
];

// Helpers de banderas / Flag helpers (flagcdn.com)
function flagUrl(code, size = "w320") {
  return `https://flagcdn.com/${size}/${code}.png`;
}

// Utilidad: barajar array (Fisher-Yates)
function shuffle(array) {
  const a = array.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// Obtener N países aleatorios distintos
function randomCountries(n, pool = COUNTRIES) {
  return shuffle(pool).slice(0, n);
}

// Filtrar por continente
function countriesByContinent(continentCode) {
  if (!continentCode || continentCode === "ALL") return COUNTRIES;
  return COUNTRIES.filter(c => c.continent === continentCode);
}

window.GEO_DATA = { CONTINENTS, COUNTRIES, flagUrl, shuffle, randomCountries, countriesByContinent };
